# Generated by Django 5.2.2 on 2025-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('productname', models.CharField(max_length=30)),
                ('productprice', models.IntegerField()),
                ('productquantity', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='product_image')),
                ('productdescription', models.CharField(max_length=30)),
                ('productcategory', models.CharField(max_length=30)),
                ('productbrand', models.CharField(max_length=30)),
                ('productcolor', models.CharField(max_length=30)),
                ('productmaterial', models.CharField(max_length=30)),
                ('productrate', models.IntegerField()),
            ],
        ),
    ]
