# Generated by Django 5.2.2 on 2025-06-10 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product_image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='productimage',
        ),
        migrations.AddField(
            model_name='customer',
            name='productimageid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='createat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
