# Generated by Django 5.2.2 on 2025-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_image_image_alter_image_name_alter_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='productrate',
            field=models.CharField(max_length=250),
        ),
    ]
