# Generated by Django 5.2.2 on 2025-06-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customer_productrate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='myapp_image',
        ),
    ]
