# Generated by Django 5.2.2 on 2025-06-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_image_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='myapp_customer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='myapp_user',
        ),
    ]
